//GENERATED BY CODE! DO NOT MODIFY!
//Network Version: 774;
package com.daniel99j.lib99j.api;

import eu.pb4.polymer.common.api.PolymerCommonUtils;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.network.protocol.PacketType;
import net.minecraft.network.protocol.common.*;
import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.Identifier;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public class GameCommonPacketList {
    private static List<PacketInfo> temp = new ArrayList<>();

    static {
        temp.add(new PacketInfo(ClientboundBundlePacket.class, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundBundleDelimiterPacket.class, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundAddEntityPacket.class, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundAnimatePacket.class, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundAwardStatsPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundBlockChangedAckPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockDestructionPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockEntityDataPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockEventPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockUpdatePacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBossEventPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundChangeDifficultyPacket.class, PacketTag.WORLD, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundChunkBatchFinishedPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundChunkBatchStartPacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundChunksBiomesPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundClearTitlesPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundCommandSuggestionsPacket.class, PacketTag.COMMAND));
        temp.add(new PacketInfo(ClientboundCommandsPacket.class, PacketTag.COMMAND));
        temp.add(new PacketInfo(ClientboundContainerClosePacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundContainerSetContentPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundContainerSetDataPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundContainerSetSlotPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundCooldownPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundCustomChatCompletionsPacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundDamageEventPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundDebugBlockValuePacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugChunkValuePacket.class, PacketTag.CHUNK, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugEntityValuePacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugEventPacket.class, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugSamplePacket.class, PacketTag.UI, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDeleteChatPacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundDisguisedChatPacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundEntityEventPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundEntityPositionSyncPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundExplodePacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundForgetLevelChunkPacket.class, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundGameEventPacket.class, PacketTag.MISC, PacketTag.PLAYER_CLIENT, PacketTag.MANY_USES));
        temp.add(new PacketInfo(ClientboundGameTestHighlightPosPacket.class, PacketTag.DEBUG, PacketTag.WORLD, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundMountScreenOpenPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundHurtAnimationPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundInitializeBorderPacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundLevelChunkWithLightPacket.class, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundLevelEventPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundLevelParticlesPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundLightUpdatePacket.class, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundLoginPacket.class, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundMapItemDataPacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundMerchantOffersPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.Pos.class, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.PosRot.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveMinecartPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.Rot.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveVehiclePacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundOpenBookPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundOpenScreenPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundOpenSignEditorPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundPlaceGhostRecipePacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundPlayerAbilitiesPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerChatPacket.class, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundPlayerCombatEndPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerCombatEnterPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerCombatKillPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerInfoRemovePacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundPlayerInfoUpdatePacket.class, PacketTag.UI, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundPlayerLookAtPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerPositionPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundPlayerRotationPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundRecipeBookAddPacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRecipeBookRemovePacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRecipeBookSettingsPacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRemoveEntitiesPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundRemoveMobEffectPacket.class, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundRespawnPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundRotateHeadPacket.class, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSectionBlocksUpdatePacket.class, PacketTag.CHUNK, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSelectAdvancementsTabPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundServerDataPacket.class, PacketTag.UI, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetActionBarTextPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetBorderCenterPacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderLerpSizePacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderSizePacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderWarningDelayPacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderWarningDistancePacket.class, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetCameraPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetChunkCacheCenterPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetChunkCacheRadiusPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetDefaultSpawnPositionPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundSetDisplayObjectivePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetEntityDataPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEntityLinkPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEntityMotionPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEquipmentPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetExperiencePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetHealthPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetHeldSlotPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetObjectivePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetPassengersPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetPlayerTeamPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetScorePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetSimulationDistancePacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetSubtitleTextPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSetTimePacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetTitleTextPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSetTitlesAnimationPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSoundEntityPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSoundPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundStartConfigurationPacket.class, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundStopSoundPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSystemChatPacket.class, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundTabListPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTagQueryPacket.class, PacketTag.MISC, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTakeItemEntityPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundTeleportEntityPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundTestInstanceBlockStatus.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundUpdateAdvancementsPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundUpdateAttributesPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundUpdateMobEffectPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundUpdateRecipesPacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundProjectilePowerPacket.class, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundTrackedWaypointPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ServerboundAcceptTeleportationPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundBlockEntityTagQueryPacket.class, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSelectBundleItemPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundChangeDifficultyPacket.class, PacketTag.WORLD, PacketTag.UI));
        temp.add(new PacketInfo(ServerboundChangeGameModePacket.class, PacketTag.WORLD, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ServerboundChatAckPacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ServerboundChatCommandPacket.class, PacketTag.CHAT, PacketTag.COMMAND));
        temp.add(new PacketInfo(ServerboundChatCommandSignedPacket.class, PacketTag.CHAT, PacketTag.COMMAND));
        temp.add(new PacketInfo(ServerboundChatPacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ServerboundChatSessionUpdatePacket.class, PacketTag.CHAT));
        temp.add(new PacketInfo(ServerboundChunkBatchReceivedPacket.class, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ServerboundClientCommandPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MISC, PacketTag.MANY_USES));
        temp.add(new PacketInfo(ServerboundClientTickEndPacket.class, PacketTag.MISC));
        temp.add(new PacketInfo(ServerboundCommandSuggestionPacket.class, PacketTag.COMMAND));
        temp.add(new PacketInfo(ServerboundConfigurationAcknowledgedPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MISC));
        temp.add(new PacketInfo(ServerboundContainerButtonClickPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundContainerClickPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundContainerClosePacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ServerboundContainerSlotStateChangedPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundDebugSubscriptionRequestPacket.class, PacketTag.DEBUG));
        temp.add(new PacketInfo(ServerboundEditBookPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundEntityTagQueryPacket.class, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ServerboundInteractPacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundJigsawGeneratePacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ServerboundLockDifficultyPacket.class, PacketTag.WORLD, PacketTag.UI));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.Pos.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.PosRot.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.Rot.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundMovePlayerPacket.StatusOnly.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundMoveVehiclePacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundPaddleBoatPacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundPickItemFromBlockPacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundPickItemFromEntityPacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundPlaceRecipePacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundPlayerAbilitiesPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundPlayerActionPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.INVENTORY, PacketTag.MANY_USES));
        temp.add(new PacketInfo(ServerboundPlayerCommandPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.ENTITY, PacketTag.MOVEMENT, PacketTag.MANY_USES));
        temp.add(new PacketInfo(ServerboundPlayerInputPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundPlayerLoadedPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.MISC));
        temp.add(new PacketInfo(ServerboundRecipeBookChangeSettingsPacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ServerboundRecipeBookSeenRecipePacket.class, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ServerboundRenameItemPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundSeenAdvancementsPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSelectTradePacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundSetBeaconPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundSetCarriedItemPacket.class, PacketTag.UI, PacketTag.INVENTORY, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSetCommandBlockPacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.COMMAND));
        temp.add(new PacketInfo(ServerboundSetCommandMinecartPacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.COMMAND));
        temp.add(new PacketInfo(ServerboundSetCreativeModeSlotPacket.class, PacketTag.UI, PacketTag.INVENTORY, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSetJigsawBlockPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ServerboundSetStructureBlockPacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ServerboundSetTestBlockPacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.DEBUG));
        temp.add(new PacketInfo(ServerboundTestInstanceBlockActionPacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.DEBUG));
        temp.add(new PacketInfo(ServerboundSignUpdatePacket.class, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ServerboundSwingPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ServerboundTeleportToEntityPacket.class, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundUseItemOnPacket.class, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.PLAYER_CLIENT, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundUseItemPacket.class, PacketTag.WORLD, PacketTag.PLAYER_CLIENT, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundResetScorePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTickingStatePacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundTickingStepPacket.class, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetCursorItemPacket.class, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundSetPlayerInventoryPacket.class, PacketTag.UI, PacketTag.INVENTORY, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundLowDiskSpaceWarningPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundGameRuleValuesPacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundAttackPacket.class, PacketTag.ENTITY, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSetGameRulePacket.class, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSpectateEntityPacket.class, PacketTag.ENTITY, PacketTag.PLAYER_CLIENT));

        temp.add(new PacketInfo(ClientboundCustomPayloadPacket.class, PacketTag.MANY_USES));
        temp.add(new PacketInfo(ServerboundCustomPayloadPacket.class, PacketTag.MANY_USES));

        temp.add(new PacketInfo(ClientboundKeepAlivePacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundClearDialogPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundCustomReportDetailsPacket.class, PacketTag.PLAYER_CLIENT, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundDisconnectPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPingPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundResourcePackPopPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundResourcePackPushPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundServerLinksPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundShowDialogPacket.class, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundStoreCookiePacket.class, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTransferPacket.class, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundUpdateTagsPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundClientInformationPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundKeepAlivePacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundPongPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundResourcePackPacket.class, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundCustomClickActionPacket.class, PacketTag.UI));
    }

    public static final List<PacketInfo> playPackets = List.copyOf(temp);

    static {
        temp = null;
    }

    public static final class PacketInfo {
        private final Class<? extends Packet<?>> packet;
        private final PacketType<?> type;
        private final PacketFlow side;
        private final PacketTag[] tags;
        private final PacketStage stage;

        public PacketInfo(Class<? extends Packet<?>> packet, PacketTag... tags) {
            this.packet = packet;
            Packet<?> unsafePacket = PolymerCommonUtils.createUnsafe(packet);
            this.type = unsafePacket.type();
            this.tags = tags;
            if(packet.toGenericString().contains("net.minecraft.network.protocol.common")) this.stage = PacketStage.COMMON;
            else if(packet.toGenericString().contains("net.minecraft.network.protocol.game")) this.stage = PacketStage.GAME;
            else throw new IllegalStateException("Unknown stage for "+packet.toGenericString());

            if(packet.toGenericString().contains("Serverbound")) this.side = PacketFlow.SERVERBOUND;
            else if(packet.toGenericString().contains("Clientbound")) this.side = PacketFlow.CLIENTBOUND;
            else throw new IllegalStateException("Unknown direction for "+packet.toGenericString());
        }

        public boolean hasTag(PacketTag tag) {
                return Arrays.stream(this.tags()).toList().contains(tag);
            }

        public Class<? extends Packet<?>> packet() {
            return packet;
        }

        public PacketType<?> type() {
            return type;
        }

        public PacketFlow side() {
            return side;
        }

        public PacketTag[] tags() {
            return tags;
        }

        public PacketStage stage() {
            return stage;
        }

        @Override
        public boolean equals(Object o) {
            if (o == null || getClass() != o.getClass()) return false;
            PacketInfo that = (PacketInfo) o;
            return Objects.equals(packet, that.packet) && Objects.equals(type, that.type) && side == that.side && Objects.deepEquals(tags, that.tags) && stage == that.stage;
        }

        @Override
        public int hashCode() {
            return Objects.hash(packet, type, side, Arrays.hashCode(tags), stage);
        }

        @Override
        public String toString() {
            return "PacketInfo{" +
                    "packet=" + packet +
                    ", type=" + type +
                    ", side=" + side +
                    ", tags=" + Arrays.toString(tags) +
                    ", stage=" + stage +
                    '}';
        }
    };

    public static @NotNull PacketInfo getInfo(Identifier id, PacketFlow direction) {
        var packets = playPackets.stream().filter((packetInfo -> packetInfo.type().id().equals(id) && packetInfo.side.equals(direction))).toList();
        if(packets.isEmpty()) throw new IllegalStateException("Packet tag not set for "+id+"! Please contact Daniel99j!");
        if(packets.size() > 1) throw new IllegalStateException("Too many packets returned for "+id+"! Please contact Daniel99j!");
        return packets.getFirst();
    }

    public static PacketInfo getInfo(PacketType<?> type) {
        return getInfo(type.id(), type.flow());
    }

    public static @NotNull PacketInfo getInfo(Packet<?> packet) {
        if(packet == null || packet.type() == null) throw new NullPointerException();
        return getInfo(packet.type());
    }
}
