//GENERATED BY CODE! DO NOT MODIFY!
//Network Version: 774;
package com.daniel99j.lib99j.api;

import net.minecraft.network.NetworkSide;
import net.minecraft.network.packet.*;
import net.minecraft.network.packet.c2s.play.*;
import net.minecraft.network.packet.s2c.play.*;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PlayPacketUtils {
    private static List<PacketInfo> temp = new ArrayList<>();

    static {
        temp.add(new PacketInfo(BundleS2CPacket.class, PlayPackets.BUNDLE, NetworkSide.CLIENTBOUND, PacketTag.MISC));
        temp.add(new PacketInfo(BundleDelimiterS2CPacket.class, PlayPackets.BUNDLE_DELIMITER, NetworkSide.CLIENTBOUND, PacketTag.MISC));
        temp.add(new PacketInfo(EntitySpawnS2CPacket.class, PlayPackets.ADD_ENTITY, NetworkSide.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(EntityAnimationS2CPacket.class, PlayPackets.ANIMATE, NetworkSide.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(StatisticsS2CPacket.class, PlayPackets.AWARD_STATS, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(PlayerActionResponseS2CPacket.class, PlayPackets.BLOCK_CHANGED_ACK, NetworkSide.CLIENTBOUND));
        temp.add(new PacketInfo(BlockBreakingProgressS2CPacket.class, PlayPackets.BLOCK_DESTRUCTION, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(BlockEntityUpdateS2CPacket.class, PlayPackets.BLOCK_ENTITY_DATA, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(BlockEventS2CPacket.class, PlayPackets.BLOCK_EVENT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(BlockUpdateS2CPacket.class, PlayPackets.BLOCK_UPDATE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(BossBarS2CPacket.class, PlayPackets.BOSS_EVENT, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(DifficultyS2CPacket.class, PlayPackets.CHANGE_DIFFICULTY_S2C, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.UI));
        temp.add(new PacketInfo(ChunkSentS2CPacket.class, PlayPackets.CHUNK_BATCH_FINISHED, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(StartChunkSendS2CPacket.class, PlayPackets.CHUNK_BATCH_START, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ChunkBiomeDataS2CPacket.class, PlayPackets.CHUNKS_BIOMES, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClearTitleS2CPacket.class, PlayPackets.CLEAR_TITLES, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(CommandSuggestionsS2CPacket.class, PlayPackets.COMMAND_SUGGESTIONS, NetworkSide.CLIENTBOUND, PacketTag.COMMAND));
        temp.add(new PacketInfo(CommandTreeS2CPacket.class, PlayPackets.COMMANDS, NetworkSide.CLIENTBOUND, PacketTag.COMMAND));
        temp.add(new PacketInfo(CloseScreenS2CPacket.class, PlayPackets.CONTAINER_CLOSE_S2C, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(InventoryS2CPacket.class, PlayPackets.CONTAINER_SET_CONTENT, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ScreenHandlerPropertyUpdateS2CPacket.class, PlayPackets.CONTAINER_SET_DATA, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ScreenHandlerSlotUpdateS2CPacket.class, PlayPackets.CONTAINER_SET_SLOT, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(CooldownUpdateS2CPacket.class, PlayPackets.COOLDOWN, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ChatSuggestionsS2CPacket.class, PlayPackets.CUSTOM_CHAT_COMPLETIONS, NetworkSide.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(EntityDamageS2CPacket.class, PlayPackets.DAMAGE_EVENT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(BlockValueDebugS2CPacket.class, PlayPackets.BLOCK_VALUE_DEBUG, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.DEBUG));
        temp.add(new PacketInfo(ChunkValueDebugS2CPacket.class, PlayPackets.CHUNK_VALUE_DEBUG, NetworkSide.CLIENTBOUND, PacketTag.CHUNK, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(EntityValueDebugS2CPacket.class, PlayPackets.ENTITY_VALUE_DEBUG, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.DEBUG));
        temp.add(new PacketInfo(EventDebugS2CPacket.class, PlayPackets.EVENT_DEBUG, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(DebugSampleS2CPacket.class, PlayPackets.DEBUG_SAMPLE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.DEBUG));
        temp.add(new PacketInfo(RemoveMessageS2CPacket.class, PlayPackets.DELETE_CHAT, NetworkSide.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(ProfilelessChatMessageS2CPacket.class, PlayPackets.DISGUISED_CHAT, NetworkSide.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(EntityStatusS2CPacket.class, PlayPackets.ENTITY_EVENT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityPositionSyncS2CPacket.class, PlayPackets.ENTITY_POSITION_SYNC, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ExplosionS2CPacket.class, PlayPackets.EXPLODE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(UnloadChunkS2CPacket.class, PlayPackets.FORGET_LEVEL_CHUNK, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(GameStateChangeS2CPacket.class, PlayPackets.GAME_EVENT, NetworkSide.CLIENTBOUND, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(GameTestHighlightPosS2CPacket.class, PlayPackets.GAME_TEST_HIGHLIGHT_POS, NetworkSide.CLIENTBOUND, PacketTag.DEBUG, PacketTag.WORLD, PacketTag.WORLD));
        temp.add(new PacketInfo(OpenMountScreenS2CPacket.class, PlayPackets.MOUNT_SCREEN_OPEN, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(DamageTiltS2CPacket.class, PlayPackets.HURT_ANIMATION, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(WorldBorderInitializeS2CPacket.class, PlayPackets.INITIALIZE_BORDER, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ChunkDataS2CPacket.class, PlayPackets.LEVEL_CHUNK_WITH_LIGHT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(WorldEventS2CPacket.class, PlayPackets.LEVEL_EVENT, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ParticleS2CPacket.class, PlayPackets.LEVEL_PARTICLES, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(LightUpdateS2CPacket.class, PlayPackets.LIGHT_UPDATE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(GameJoinS2CPacket.class, PlayPackets.LOGIN, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(MapUpdateS2CPacket.class, PlayPackets.MAP_ITEM_DATA, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(SetTradeOffersS2CPacket.class, PlayPackets.MERCHANT_OFFERS, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(EntityS2CPacket.MoveRelative.class, PlayPackets.MOVE_ENTITY_POS, NetworkSide.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(EntityS2CPacket.RotateAndMoveRelative.class, PlayPackets.MOVE_ENTITY_POS_ROT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(MoveMinecartAlongTrackS2CPacket.class, PlayPackets.MOVE_MINECART_ALONG_TRACK, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityS2CPacket.Rotate.class, PlayPackets.MOVE_ENTITY_ROT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(VehicleMoveS2CPacket.class, PlayPackets.MOVE_VEHICLE_S2C, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(OpenWrittenBookS2CPacket.class, PlayPackets.OPEN_BOOK, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(OpenScreenS2CPacket.class, PlayPackets.OPEN_SCREEN, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(SignEditorOpenS2CPacket.class, PlayPackets.OPEN_SIGN_EDITOR, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(CraftFailedResponseS2CPacket.class, PlayPackets.PLACE_GHOST_RECIPE, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(PlayerAbilitiesS2CPacket.class, PlayPackets.PLAYER_ABILITIES_S2C, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ChatMessageS2CPacket.class, PlayPackets.PLAYER_CHAT, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(EndCombatS2CPacket.class, PlayPackets.PLAYER_COMBAT_END, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(EnterCombatS2CPacket.class, PlayPackets.PLAYER_COMBAT_ENTER, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(DeathMessageS2CPacket.class, PlayPackets.PLAYER_COMBAT_KILL, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(PlayerRemoveS2CPacket.class, PlayPackets.PLAYER_INFO_REMOVE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(PlayerListS2CPacket.class, PlayPackets.PLAYER_INFO_UPDATE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(LookAtS2CPacket.class, PlayPackets.PLAYER_LOOK_AT, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(PlayerPositionLookS2CPacket.class, PlayPackets.PLAYER_POSITION, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(PlayerRotationS2CPacket.class, PlayPackets.PLAYER_ROTATION, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(RecipeBookAddS2CPacket.class, PlayPackets.RECIPE_BOOK_ADD, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(RecipeBookRemoveS2CPacket.class, PlayPackets.RECIPE_BOOK_REMOVE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(RecipeBookSettingsS2CPacket.class, PlayPackets.RECIPE_BOOK_SETTINGS, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(EntitiesDestroyS2CPacket.class, PlayPackets.REMOVE_ENTITIES, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(RemoveEntityStatusEffectS2CPacket.class, PlayPackets.REMOVE_MOB_EFFECT, NetworkSide.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(PlayerRespawnS2CPacket.class, PlayPackets.RESPAWN, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(EntitySetHeadYawS2CPacket.class, PlayPackets.ROTATE_HEAD, NetworkSide.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ChunkDeltaUpdateS2CPacket.class, PlayPackets.SECTION_BLOCKS_UPDATE, NetworkSide.CLIENTBOUND, PacketTag.CHUNK, PacketTag.WORLD));
        temp.add(new PacketInfo(SelectAdvancementTabS2CPacket.class, PlayPackets.SELECT_ADVANCEMENTS_TAB, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerMetadataS2CPacket.class, PlayPackets.SERVER_DATA, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(OverlayMessageS2CPacket.class, PlayPackets.SET_ACTION_BAR_TEXT, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(WorldBorderCenterChangedS2CPacket.class, PlayPackets.SET_BORDER_CENTER, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(WorldBorderInterpolateSizeS2CPacket.class, PlayPackets.SET_BORDER_LERP_SIZE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(WorldBorderSizeChangedS2CPacket.class, PlayPackets.SET_BORDER_SIZE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(WorldBorderWarningTimeChangedS2CPacket.class, PlayPackets.SET_BORDER_WARNING_DELAY, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(WorldBorderWarningBlocksChangedS2CPacket.class, PlayPackets.SET_BORDER_WARNING_DISTANCE, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(SetCameraEntityS2CPacket.class, PlayPackets.SET_CAMERA, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ChunkRenderDistanceCenterS2CPacket.class, PlayPackets.SET_CHUNK_CACHE_CENTER, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ChunkLoadDistanceS2CPacket.class, PlayPackets.SET_CHUNK_CACHE_RADIUS, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(PlayerSpawnPositionS2CPacket.class, PlayPackets.SET_DEFAULT_SPAWN_POSITION, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ScoreboardDisplayS2CPacket.class, PlayPackets.SET_DISPLAY_OBJECTIVE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(EntityTrackerUpdateS2CPacket.class, PlayPackets.SET_ENTITY_DATA, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityAttachS2CPacket.class, PlayPackets.SET_ENTITY_LINK, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityVelocityUpdateS2CPacket.class, PlayPackets.SET_ENTITY_MOTION, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityEquipmentUpdateS2CPacket.class, PlayPackets.SET_EQUIPMENT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ExperienceBarUpdateS2CPacket.class, PlayPackets.SET_EXPERIENCE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(HealthUpdateS2CPacket.class, PlayPackets.SET_HEALTH, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(UpdateSelectedSlotS2CPacket.class, PlayPackets.SET_CARRIED_ITEM_S2C, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ScoreboardObjectiveUpdateS2CPacket.class, PlayPackets.SET_OBJECTIVE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(EntityPassengersSetS2CPacket.class, PlayPackets.SET_PASSENGERS, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(TeamS2CPacket.class, PlayPackets.SET_PLAYER_TEAM, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ScoreboardScoreUpdateS2CPacket.class, PlayPackets.SET_SCORE, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(SimulationDistanceS2CPacket.class, PlayPackets.SET_SIMULATION_DISTANCE, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(SubtitleS2CPacket.class, PlayPackets.SET_SUBTITLE_TEXT, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(WorldTimeUpdateS2CPacket.class, PlayPackets.SET_TIME, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(TitleS2CPacket.class, PlayPackets.SET_TITLE_TEXT, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(TitleFadeS2CPacket.class, PlayPackets.SET_TITLES_ANIMATION, NetworkSide.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(PlaySoundFromEntityS2CPacket.class, PlayPackets.SOUND_ENTITY, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(PlaySoundS2CPacket.class, PlayPackets.SOUND, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(EnterReconfigurationS2CPacket.class, PlayPackets.START_CONFIGURATION, NetworkSide.CLIENTBOUND, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(StopSoundS2CPacket.class, PlayPackets.STOP_SOUND, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(GameMessageS2CPacket.class, PlayPackets.SYSTEM_CHAT, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(PlayerListHeaderS2CPacket.class, PlayPackets.TAB_LIST, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(NbtQueryResponseS2CPacket.class, PlayPackets.TAG_QUERY, NetworkSide.CLIENTBOUND, PacketTag.MISC, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ItemPickupAnimationS2CPacket.class, PlayPackets.TAKE_ITEM_ENTITY, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.WORLD));
        temp.add(new PacketInfo(EntityPositionS2CPacket.class, PlayPackets.TELEPORT_ENTITY, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(TestInstanceBlockStatusS2CPacket.class, PlayPackets.TEST_INSTANCE_BLOCK_STATUS, NetworkSide.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(AdvancementUpdateS2CPacket.class, PlayPackets.UPDATE_ADVANCEMENTS, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(EntityAttributesS2CPacket.class, PlayPackets.UPDATE_ATTRIBUTES, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(EntityStatusEffectS2CPacket.class, PlayPackets.UPDATE_MOB_EFFECT, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(SynchronizeRecipesS2CPacket.class, PlayPackets.UPDATE_RECIPES, NetworkSide.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ProjectilePowerS2CPacket.class, PlayPackets.PROJECTILE_POWER, NetworkSide.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(WaypointS2CPacket.class, PlayPackets.WAYPOINT, NetworkSide.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(TeleportConfirmC2SPacket.class, PlayPackets.ACCEPT_TELEPORTATION, NetworkSide.SERVERBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(QueryBlockNbtC2SPacket.class, PlayPackets.BLOCK_ENTITY_TAG_QUERY, NetworkSide.SERVERBOUND, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(BundleItemSelectedC2SPacket.class, PlayPackets.BUNDLE_ITEM_SELECTED, NetworkSide.SERVERBOUND, PacketTag.PLAYER_CLIENT, PacketTag.INVENTORY));
        temp.add(new PacketInfo(UpdateDifficultyC2SPacket.class, PlayPackets.CHANGE_DIFFICULTY_C2S, NetworkSide.SERVERBOUND, PacketTag.WORLD, PacketTag.ENTITY)); //TODO: FINISH!
        temp.add(new PacketInfo(ChangeGameModeC2SPacket.class, PlayPackets.CHANGE_GAME_MODE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(MessageAcknowledgmentC2SPacket.class, PlayPackets.CHAT_ACK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(CommandExecutionC2SPacket.class, PlayPackets.CHAT_COMMAND, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ChatCommandSignedC2SPacket.class, PlayPackets.CHAT_COMMAND_SIGNED, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ChatMessageC2SPacket.class, PlayPackets.CHAT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerSessionC2SPacket.class, PlayPackets.CHAT_SESSION_UPDATE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(AcknowledgeChunksC2SPacket.class, PlayPackets.CHUNK_BATCH_RECEIVED, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ClientStatusC2SPacket.class, PlayPackets.CLIENT_COMMAND, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ClientTickEndC2SPacket.class, PlayPackets.CLIENT_TICK_END, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(RequestCommandCompletionsC2SPacket.class, PlayPackets.COMMAND_SUGGESTION, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(AcknowledgeReconfigurationC2SPacket.class, PlayPackets.CONFIGURATION_ACKNOWLEDGED, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ButtonClickC2SPacket.class, PlayPackets.CONTAINER_BUTTON_CLICK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ClickSlotC2SPacket.class, PlayPackets.CONTAINER_CLICK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(CloseHandledScreenC2SPacket.class, PlayPackets.CONTAINER_CLOSE_C2S, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(SlotChangedStateC2SPacket.class, PlayPackets.CONTAINER_SLOT_STATE_CHANGED, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(DebugSubscriptionRequestC2SPacket.class, PlayPackets.DEBUG_SUBSCRIPTION_REQUEST, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(BookUpdateC2SPacket.class, PlayPackets.EDIT_BOOK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(QueryEntityNbtC2SPacket.class, PlayPackets.ENTITY_TAG_QUERY, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerInteractEntityC2SPacket.class, PlayPackets.INTERACT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(JigsawGeneratingC2SPacket.class, PlayPackets.JIGSAW_GENERATE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateDifficultyLockC2SPacket.class, PlayPackets.LOCK_DIFFICULTY, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerMoveC2SPacket.PositionAndOnGround.class, PlayPackets.MOVE_PLAYER_POS, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerMoveC2SPacket.Full.class, PlayPackets.MOVE_PLAYER_POS_ROT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerMoveC2SPacket.LookAndOnGround.class, PlayPackets.MOVE_PLAYER_ROT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerMoveC2SPacket.OnGroundOnly.class, PlayPackets.MOVE_PLAYER_STATUS_ONLY, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(VehicleMoveC2SPacket.class, PlayPackets.MOVE_VEHICLE_C2S, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(BoatPaddleStateC2SPacket.class, PlayPackets.PADDLE_BOAT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PickItemFromBlockC2SPacket.class, PlayPackets.PICK_ITEM_FROM_BLOCK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PickItemFromEntityC2SPacket.class, PlayPackets.PICK_ITEM_FROM_ENTITY, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(CraftRequestC2SPacket.class, PlayPackets.PLACE_RECIPE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdatePlayerAbilitiesC2SPacket.class, PlayPackets.PLAYER_ABILITIES_C2S, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerActionC2SPacket.class, PlayPackets.PLAYER_ACTION, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ClientCommandC2SPacket.class, PlayPackets.PLAYER_COMMAND, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerInputC2SPacket.class, PlayPackets.PLAYER_INPUT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerLoadedC2SPacket.class, PlayPackets.PLAYER_LOADED, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(RecipeCategoryOptionsC2SPacket.class, PlayPackets.RECIPE_BOOK_CHANGE_SETTINGS, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(RecipeBookDataC2SPacket.class, PlayPackets.RECIPE_BOOK_SEEN_RECIPE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(RenameItemC2SPacket.class, PlayPackets.RENAME_ITEM, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(AdvancementTabC2SPacket.class, PlayPackets.SEEN_ADVANCEMENTS, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(SelectMerchantTradeC2SPacket.class, PlayPackets.SELECT_TRADE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateBeaconC2SPacket.class, PlayPackets.SET_BEACON, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateSelectedSlotC2SPacket.class, PlayPackets.SET_CARRIED_ITEM_C2S, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateCommandBlockC2SPacket.class, PlayPackets.SET_COMMAND_BLOCK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateCommandBlockMinecartC2SPacket.class, PlayPackets.SET_COMMAND_MINECART, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(CreativeInventoryActionC2SPacket.class, PlayPackets.SET_CREATIVE_MODE_SLOT, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateJigsawC2SPacket.class, PlayPackets.SET_JIGSAW_BLOCK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateStructureBlockC2SPacket.class, PlayPackets.SET_STRUCTURE_BLOCK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(SetTestBlockC2SPacket.class, PlayPackets.SET_TEST_BLOCK, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(TestInstanceBlockActionC2SPacket.class, PlayPackets.TEST_INSTANCE_BLOCK_ACTION, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(UpdateSignC2SPacket.class, PlayPackets.SIGN_UPDATE, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(HandSwingC2SPacket.class, PlayPackets.SWING, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(SpectatorTeleportC2SPacket.class, PlayPackets.TELEPORT_TO_ENTITY, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerInteractBlockC2SPacket.class, PlayPackets.USE_ITEM_ON, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(PlayerInteractItemC2SPacket.class, PlayPackets.USE_ITEM, NetworkSide.SERVERBOUND));
        temp.add(new PacketInfo(ScoreboardScoreResetS2CPacket.class, PlayPackets.RESET_SCORE, NetworkSide.CLIENTBOUND));
        temp.add(new PacketInfo(UpdateTickRateS2CPacket.class, PlayPackets.TICKING_STATE, NetworkSide.CLIENTBOUND));
        temp.add(new PacketInfo(TickStepS2CPacket.class, PlayPackets.TICKING_STEP, NetworkSide.CLIENTBOUND));
        temp.add(new PacketInfo(SetCursorItemS2CPacket.class, PlayPackets.SET_CURSOR_ITEM, NetworkSide.CLIENTBOUND));
        temp.add(new PacketInfo(SetPlayerInventoryS2CPacket.class, PlayPackets.SET_PLAYER_INVENTORY, NetworkSide.CLIENTBOUND));
    }

    public static final List<PacketInfo> playPackets = List.copyOf(temp);

    static {
        temp = null;
    }

    public record PacketInfo(Class<? extends Packet<?>> packet, PacketType<?> type, NetworkSide side, PacketTag... tags) {
        public boolean hasTag(PacketTag tag) {
            return Arrays.stream(this.tags()).toList().contains(tag);
        }
    };

    public enum PacketTag {
        CHUNK,
        WORLD,
        ENTITY,
        PLAYER_ANY,
        PLAYER_CLIENT,
        INVENTORY,
        MOVEMENT,
        BLOCK,
        UI,
        DEBUG,
        MISC,
        CHAT,
        COMMAND
    }

    public static @Nullable PacketInfo getInfo(Identifier id) {
        var packets = playPackets.stream().filter((packetInfo -> packetInfo.type().id().equals(id))).toList();
        return packets.isEmpty() ? null : packets.getFirst();
    }

    public static PacketInfo getInfo(PacketType<?> type) {
        return getInfo(type.id());
    }

    public static PacketInfo getInfo(Packet<?> packet) {
        if(packet == null || packet.getPacketType() == null) return null;
        return getInfo(packet.getPacketType());
    }
}
