//GENERATED BY CODE! DO NOT MODIFY!
//Network Version: 774;
package com.daniel99j.lib99j.api;

import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.network.protocol.PacketType;
import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.Identifier;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PlayPacketUtils {
    private static List<PacketInfo> temp = new ArrayList<>();

    static {
        temp.add(new PacketInfo(ClientboundBundlePacket.class, GamePacketTypes.CLIENTBOUND_BUNDLE, PacketFlow.CLIENTBOUND, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundBundleDelimiterPacket.class, GamePacketTypes.CLIENTBOUND_BUNDLE_DELIMITER, PacketFlow.CLIENTBOUND, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundAddEntityPacket.class, GamePacketTypes.CLIENTBOUND_ADD_ENTITY, PacketFlow.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundAnimatePacket.class, GamePacketTypes.CLIENTBOUND_ANIMATE, PacketFlow.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundAwardStatsPacket.class, GamePacketTypes.CLIENTBOUND_AWARD_STATS, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundBlockChangedAckPacket.class, GamePacketTypes.CLIENTBOUND_BLOCK_CHANGED_ACK, PacketFlow.CLIENTBOUND));
        temp.add(new PacketInfo(ClientboundBlockDestructionPacket.class, GamePacketTypes.CLIENTBOUND_BLOCK_DESTRUCTION, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockEntityDataPacket.class, GamePacketTypes.CLIENTBOUND_BLOCK_ENTITY_DATA, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockEventPacket.class, GamePacketTypes.CLIENTBOUND_BLOCK_EVENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBlockUpdatePacket.class, GamePacketTypes.CLIENTBOUND_BLOCK_UPDATE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK));
        temp.add(new PacketInfo(ClientboundBossEventPacket.class, GamePacketTypes.CLIENTBOUND_BOSS_EVENT, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundChangeDifficultyPacket.class, GamePacketTypes.CLIENTBOUND_CHANGE_DIFFICULTY, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundChunkBatchFinishedPacket.class, GamePacketTypes.CLIENTBOUND_CHUNK_BATCH_FINISHED, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundChunkBatchStartPacket.class, GamePacketTypes.CLIENTBOUND_CHUNK_BATCH_START, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundChunksBiomesPacket.class, GamePacketTypes.CLIENTBOUND_CHUNKS_BIOMES, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundClearTitlesPacket.class, GamePacketTypes.CLIENTBOUND_CLEAR_TITLES, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundCommandSuggestionsPacket.class, GamePacketTypes.CLIENTBOUND_COMMAND_SUGGESTIONS, PacketFlow.CLIENTBOUND, PacketTag.COMMAND));
        temp.add(new PacketInfo(ClientboundCommandsPacket.class, GamePacketTypes.CLIENTBOUND_COMMANDS, PacketFlow.CLIENTBOUND, PacketTag.COMMAND));
        temp.add(new PacketInfo(ClientboundContainerClosePacket.class, GamePacketTypes.CLIENTBOUND_CONTAINER_CLOSE, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundContainerSetContentPacket.class, GamePacketTypes.CLIENTBOUND_CONTAINER_SET_CONTENT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundContainerSetDataPacket.class, GamePacketTypes.CLIENTBOUND_CONTAINER_SET_DATA, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundContainerSetSlotPacket.class, GamePacketTypes.CLIENTBOUND_CONTAINER_SET_SLOT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ClientboundCooldownPacket.class, GamePacketTypes.CLIENTBOUND_COOLDOWN, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundCustomChatCompletionsPacket.class, GamePacketTypes.CLIENTBOUND_CUSTOM_CHAT_COMPLETIONS, PacketFlow.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundDamageEventPacket.class, GamePacketTypes.CLIENTBOUND_DAMAGE_EVENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundDebugBlockValuePacket.class, GamePacketTypes.CLIENTBOUND_DEBUG_BLOCK_VALUE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.BLOCK, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugChunkValuePacket.class, GamePacketTypes.CLIENTBOUND_DEBUG_CHUNK_VALUE, PacketFlow.CLIENTBOUND, PacketTag.CHUNK, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugEntityValuePacket.class, GamePacketTypes.CLIENTBOUND_DEBUG_ENTITY_VALUE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugEventPacket.class, GamePacketTypes.CLIENTBOUND_DEBUG_EVENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDebugSamplePacket.class, GamePacketTypes.CLIENTBOUND_DEBUG_SAMPLE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.DEBUG));
        temp.add(new PacketInfo(ClientboundDeleteChatPacket.class, GamePacketTypes.CLIENTBOUND_DELETE_CHAT, PacketFlow.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundDisguisedChatPacket.class, GamePacketTypes.CLIENTBOUND_DISGUISED_CHAT, PacketFlow.CLIENTBOUND, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundEntityEventPacket.class, GamePacketTypes.CLIENTBOUND_ENTITY_EVENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundEntityPositionSyncPacket.class, GamePacketTypes.CLIENTBOUND_ENTITY_POSITION_SYNC, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundExplodePacket.class, GamePacketTypes.CLIENTBOUND_EXPLODE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundForgetLevelChunkPacket.class, GamePacketTypes.CLIENTBOUND_FORGET_LEVEL_CHUNK, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundGameEventPacket.class, GamePacketTypes.CLIENTBOUND_GAME_EVENT, PacketFlow.CLIENTBOUND, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundGameTestHighlightPosPacket.class, GamePacketTypes.CLIENTBOUND_GAME_TEST_HIGHLIGHT_POS, PacketFlow.CLIENTBOUND, PacketTag.DEBUG, PacketTag.WORLD, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundMountScreenOpenPacket.class, GamePacketTypes.CLIENTBOUND_MOUNT_SCREEN_OPEN, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundHurtAnimationPacket.class, GamePacketTypes.CLIENTBOUND_HURT_ANIMATION, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundInitializeBorderPacket.class, GamePacketTypes.CLIENTBOUND_INITIALIZE_BORDER, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundLevelChunkWithLightPacket.class, GamePacketTypes.CLIENTBOUND_LEVEL_CHUNK_WITH_LIGHT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundLevelEventPacket.class, GamePacketTypes.CLIENTBOUND_LEVEL_EVENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundLevelParticlesPacket.class, GamePacketTypes.CLIENTBOUND_LEVEL_PARTICLES, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundLightUpdatePacket.class, GamePacketTypes.CLIENTBOUND_LIGHT_UPDATE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.CHUNK));
        temp.add(new PacketInfo(ClientboundLoginPacket.class, GamePacketTypes.CLIENTBOUND_LOGIN, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundMapItemDataPacket.class, GamePacketTypes.CLIENTBOUND_MAP_ITEM_DATA, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundMerchantOffersPacket.class, GamePacketTypes.CLIENTBOUND_MERCHANT_OFFERS, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.Pos.class, GamePacketTypes.CLIENTBOUND_MOVE_ENTITY_POS, PacketFlow.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.PosRot.class, GamePacketTypes.CLIENTBOUND_MOVE_ENTITY_POS_ROT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveMinecartPacket.class, GamePacketTypes.CLIENTBOUND_MOVE_MINECART_ALONG_TRACK, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveEntityPacket.Rot.class, GamePacketTypes.CLIENTBOUND_MOVE_ENTITY_ROT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundMoveVehiclePacket.class, GamePacketTypes.CLIENTBOUND_MOVE_VEHICLE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundOpenBookPacket.class, GamePacketTypes.CLIENTBOUND_OPEN_BOOK, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundOpenScreenPacket.class, GamePacketTypes.CLIENTBOUND_OPEN_SCREEN, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundOpenSignEditorPacket.class, GamePacketTypes.CLIENTBOUND_OPEN_SIGN_EDITOR, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundPlaceGhostRecipePacket.class, GamePacketTypes.CLIENTBOUND_PLACE_GHOST_RECIPE, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundPlayerAbilitiesPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_ABILITIES, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerChatPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_CHAT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundPlayerCombatEndPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_COMBAT_END, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerCombatEnterPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_COMBAT_ENTER, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerCombatKillPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_COMBAT_KILL, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerInfoRemovePacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_INFO_REMOVE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundPlayerInfoUpdatePacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_INFO_UPDATE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_ANY));
        temp.add(new PacketInfo(ClientboundPlayerLookAtPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_LOOK_AT, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundPlayerPositionPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_POSITION, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundPlayerRotationPacket.class, GamePacketTypes.CLIENTBOUND_PLAYER_ROTATION, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundRecipeBookAddPacket.class, GamePacketTypes.CLIENTBOUND_RECIPE_BOOK_ADD, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRecipeBookRemovePacket.class, GamePacketTypes.CLIENTBOUND_RECIPE_BOOK_REMOVE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRecipeBookSettingsPacket.class, GamePacketTypes.CLIENTBOUND_RECIPE_BOOK_SETTINGS, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundRemoveEntitiesPacket.class, GamePacketTypes.CLIENTBOUND_REMOVE_ENTITIES, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundRemoveMobEffectPacket.class, GamePacketTypes.CLIENTBOUND_REMOVE_MOB_EFFECT, PacketFlow.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundRespawnPacket.class, GamePacketTypes.CLIENTBOUND_RESPAWN, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundRotateHeadPacket.class, GamePacketTypes.CLIENTBOUND_ROTATE_HEAD, PacketFlow.CLIENTBOUND, PacketTag.ENTITY, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSectionBlocksUpdatePacket.class, GamePacketTypes.CLIENTBOUND_SECTION_BLOCKS_UPDATE, PacketFlow.CLIENTBOUND, PacketTag.CHUNK, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSelectAdvancementsTabPacket.class, GamePacketTypes.CLIENTBOUND_SELECT_ADVANCEMENTS_TAB, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundServerDataPacket.class, GamePacketTypes.CLIENTBOUND_SERVER_DATA, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetActionBarTextPacket.class, GamePacketTypes.CLIENTBOUND_SET_ACTION_BAR_TEXT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetBorderCenterPacket.class, GamePacketTypes.CLIENTBOUND_SET_BORDER_CENTER, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderLerpSizePacket.class, GamePacketTypes.CLIENTBOUND_SET_BORDER_LERP_SIZE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderSizePacket.class, GamePacketTypes.CLIENTBOUND_SET_BORDER_SIZE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderWarningDelayPacket.class, GamePacketTypes.CLIENTBOUND_SET_BORDER_WARNING_DELAY, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetBorderWarningDistancePacket.class, GamePacketTypes.CLIENTBOUND_SET_BORDER_WARNING_DISTANCE, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundSetCameraPacket.class, GamePacketTypes.CLIENTBOUND_SET_CAMERA, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetChunkCacheCenterPacket.class, GamePacketTypes.CLIENTBOUND_SET_CHUNK_CACHE_CENTER, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetChunkCacheRadiusPacket.class, GamePacketTypes.CLIENTBOUND_SET_CHUNK_CACHE_RADIUS, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetDefaultSpawnPositionPacket.class, GamePacketTypes.CLIENTBOUND_SET_DEFAULT_SPAWN_POSITION, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ClientboundSetDisplayObjectivePacket.class, GamePacketTypes.CLIENTBOUND_SET_DISPLAY_OBJECTIVE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetEntityDataPacket.class, GamePacketTypes.CLIENTBOUND_SET_ENTITY_DATA, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEntityLinkPacket.class, GamePacketTypes.CLIENTBOUND_SET_ENTITY_LINK, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEntityMotionPacket.class, GamePacketTypes.CLIENTBOUND_SET_ENTITY_MOTION, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetEquipmentPacket.class, GamePacketTypes.CLIENTBOUND_SET_EQUIPMENT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetExperiencePacket.class, GamePacketTypes.CLIENTBOUND_SET_EXPERIENCE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetHealthPacket.class, GamePacketTypes.CLIENTBOUND_SET_HEALTH, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetHeldSlotPacket.class, GamePacketTypes.CLIENTBOUND_SET_HELD_SLOT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetObjectivePacket.class, GamePacketTypes.CLIENTBOUND_SET_OBJECTIVE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetPassengersPacket.class, GamePacketTypes.CLIENTBOUND_SET_PASSENGERS, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetPlayerTeamPacket.class, GamePacketTypes.CLIENTBOUND_SET_PLAYER_TEAM, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSetScorePacket.class, GamePacketTypes.CLIENTBOUND_SET_SCORE, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundSetSimulationDistancePacket.class, GamePacketTypes.CLIENTBOUND_SET_SIMULATION_DISTANCE, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetSubtitleTextPacket.class, GamePacketTypes.CLIENTBOUND_SET_SUBTITLE_TEXT, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSetTimePacket.class, GamePacketTypes.CLIENTBOUND_SET_TIME, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSetTitleTextPacket.class, GamePacketTypes.CLIENTBOUND_SET_TITLE_TEXT, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSetTitlesAnimationPacket.class, GamePacketTypes.CLIENTBOUND_SET_TITLES_ANIMATION, PacketFlow.CLIENTBOUND, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundSoundEntityPacket.class, GamePacketTypes.CLIENTBOUND_SOUND_ENTITY, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundSoundPacket.class, GamePacketTypes.CLIENTBOUND_SOUND, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundStartConfigurationPacket.class, GamePacketTypes.CLIENTBOUND_START_CONFIGURATION, PacketFlow.CLIENTBOUND, PacketTag.MISC, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundStopSoundPacket.class, GamePacketTypes.CLIENTBOUND_STOP_SOUND, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundSystemChatPacket.class, GamePacketTypes.CLIENTBOUND_SYSTEM_CHAT, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.CHAT));
        temp.add(new PacketInfo(ClientboundTabListPacket.class, GamePacketTypes.CLIENTBOUND_TAB_LIST, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTagQueryPacket.class, GamePacketTypes.CLIENTBOUND_TAG_QUERY, PacketFlow.CLIENTBOUND, PacketTag.MISC, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ClientboundTakeItemEntityPacket.class, GamePacketTypes.CLIENTBOUND_TAKE_ITEM_ENTITY, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundTeleportEntityPacket.class, GamePacketTypes.CLIENTBOUND_TELEPORT_ENTITY, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundTestInstanceBlockStatus.class, GamePacketTypes.CLIENTBOUND_TEST_INSTANCE_BLOCK_STATUS, PacketFlow.CLIENTBOUND, PacketTag.WORLD));
        temp.add(new PacketInfo(ClientboundUpdateAdvancementsPacket.class, GamePacketTypes.CLIENTBOUND_UPDATE_ADVANCEMENTS, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ClientboundUpdateAttributesPacket.class, GamePacketTypes.CLIENTBOUND_UPDATE_ATTRIBUTES, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundUpdateMobEffectPacket.class, GamePacketTypes.CLIENTBOUND_UPDATE_MOB_EFFECT, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundUpdateRecipesPacket.class, GamePacketTypes.CLIENTBOUND_UPDATE_RECIPES, PacketFlow.CLIENTBOUND, PacketTag.UI, PacketTag.MISC));
        temp.add(new PacketInfo(ClientboundProjectilePowerPacket.class, GamePacketTypes.CLIENTBOUND_PROJECTILE_POWER, PacketFlow.CLIENTBOUND, PacketTag.WORLD, PacketTag.ENTITY));
        temp.add(new PacketInfo(ClientboundTrackedWaypointPacket.class, GamePacketTypes.CLIENTBOUND_WAYPOINT, PacketFlow.CLIENTBOUND, PacketTag.PLAYER_CLIENT, PacketTag.UI));
        temp.add(new PacketInfo(ServerboundAcceptTeleportationPacket.class, GamePacketTypes.SERVERBOUND_ACCEPT_TELEPORTATION, PacketFlow.SERVERBOUND, PacketTag.PLAYER_CLIENT, PacketTag.MOVEMENT));
        temp.add(new PacketInfo(ServerboundBlockEntityTagQueryPacket.class, GamePacketTypes.SERVERBOUND_BLOCK_ENTITY_TAG_QUERY, PacketFlow.SERVERBOUND, PacketTag.DEBUG, PacketTag.PLAYER_CLIENT));
        temp.add(new PacketInfo(ServerboundSelectBundleItemPacket.class, GamePacketTypes.SERVERBOUND_BUNDLE_ITEM_SELECTED, PacketFlow.SERVERBOUND, PacketTag.PLAYER_CLIENT, PacketTag.INVENTORY));
        temp.add(new PacketInfo(ServerboundChangeDifficultyPacket.class, GamePacketTypes.SERVERBOUND_CHANGE_DIFFICULTY, PacketFlow.SERVERBOUND, PacketTag.WORLD, PacketTag.ENTITY)); //TODO: FINISH!
        temp.add(new PacketInfo(ServerboundChangeGameModePacket.class, GamePacketTypes.SERVERBOUND_CHANGE_GAME_MODE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChatAckPacket.class, GamePacketTypes.SERVERBOUND_CHAT_ACK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChatCommandPacket.class, GamePacketTypes.SERVERBOUND_CHAT_COMMAND, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChatCommandSignedPacket.class, GamePacketTypes.SERVERBOUND_CHAT_COMMAND_SIGNED, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChatPacket.class, GamePacketTypes.SERVERBOUND_CHAT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChatSessionUpdatePacket.class, GamePacketTypes.SERVERBOUND_CHAT_SESSION_UPDATE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundChunkBatchReceivedPacket.class, GamePacketTypes.SERVERBOUND_CHUNK_BATCH_RECEIVED, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundClientCommandPacket.class, GamePacketTypes.SERVERBOUND_CLIENT_COMMAND, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundClientTickEndPacket.class, GamePacketTypes.SERVERBOUND_CLIENT_TICK_END, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundCommandSuggestionPacket.class, GamePacketTypes.SERVERBOUND_COMMAND_SUGGESTION, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundConfigurationAcknowledgedPacket.class, GamePacketTypes.SERVERBOUND_CONFIGURATION_ACKNOWLEDGED, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundContainerButtonClickPacket.class, GamePacketTypes.SERVERBOUND_CONTAINER_BUTTON_CLICK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundContainerClickPacket.class, GamePacketTypes.SERVERBOUND_CONTAINER_CLICK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundContainerClosePacket.class, GamePacketTypes.SERVERBOUND_CONTAINER_CLOSE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundContainerSlotStateChangedPacket.class, GamePacketTypes.SERVERBOUND_CONTAINER_SLOT_STATE_CHANGED, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundDebugSubscriptionRequestPacket.class, GamePacketTypes.SERVERBOUND_DEBUG_SUBSCRIPTION_REQUEST, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundEditBookPacket.class, GamePacketTypes.SERVERBOUND_EDIT_BOOK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundEntityTagQueryPacket.class, GamePacketTypes.SERVERBOUND_ENTITY_TAG_QUERY, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundInteractPacket.class, GamePacketTypes.SERVERBOUND_INTERACT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundJigsawGeneratePacket.class, GamePacketTypes.SERVERBOUND_JIGSAW_GENERATE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundLockDifficultyPacket.class, GamePacketTypes.SERVERBOUND_LOCK_DIFFICULTY, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.Pos.class, GamePacketTypes.SERVERBOUND_MOVE_PLAYER_POS, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.PosRot.class, GamePacketTypes.SERVERBOUND_MOVE_PLAYER_POS_ROT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.Rot.class, GamePacketTypes.SERVERBOUND_MOVE_PLAYER_ROT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundMovePlayerPacket.StatusOnly.class, GamePacketTypes.SERVERBOUND_MOVE_PLAYER_STATUS_ONLY, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundMoveVehiclePacket.class, GamePacketTypes.SERVERBOUND_MOVE_VEHICLE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPaddleBoatPacket.class, GamePacketTypes.SERVERBOUND_PADDLE_BOAT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPickItemFromBlockPacket.class, GamePacketTypes.SERVERBOUND_PICK_ITEM_FROM_BLOCK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPickItemFromEntityPacket.class, GamePacketTypes.SERVERBOUND_PICK_ITEM_FROM_ENTITY, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlaceRecipePacket.class, GamePacketTypes.SERVERBOUND_PLACE_RECIPE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlayerAbilitiesPacket.class, GamePacketTypes.SERVERBOUND_PLAYER_ABILITIES, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlayerActionPacket.class, GamePacketTypes.SERVERBOUND_PLAYER_ACTION, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlayerCommandPacket.class, GamePacketTypes.SERVERBOUND_PLAYER_COMMAND, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlayerInputPacket.class, GamePacketTypes.SERVERBOUND_PLAYER_INPUT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundPlayerLoadedPacket.class, GamePacketTypes.SERVERBOUND_PLAYER_LOADED, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundRecipeBookChangeSettingsPacket.class, GamePacketTypes.SERVERBOUND_RECIPE_BOOK_CHANGE_SETTINGS, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundRecipeBookSeenRecipePacket.class, GamePacketTypes.SERVERBOUND_RECIPE_BOOK_SEEN_RECIPE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundRenameItemPacket.class, GamePacketTypes.SERVERBOUND_RENAME_ITEM, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSeenAdvancementsPacket.class, GamePacketTypes.SERVERBOUND_SEEN_ADVANCEMENTS, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSelectTradePacket.class, GamePacketTypes.SERVERBOUND_SELECT_TRADE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetBeaconPacket.class, GamePacketTypes.SERVERBOUND_SET_BEACON, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetCarriedItemPacket.class, GamePacketTypes.SERVERBOUND_SET_CARRIED_ITEM, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetCommandBlockPacket.class, GamePacketTypes.SERVERBOUND_SET_COMMAND_BLOCK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetCommandMinecartPacket.class, GamePacketTypes.SERVERBOUND_SET_COMMAND_MINECART, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetCreativeModeSlotPacket.class, GamePacketTypes.SERVERBOUND_SET_CREATIVE_MODE_SLOT, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetJigsawBlockPacket.class, GamePacketTypes.SERVERBOUND_SET_JIGSAW_BLOCK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetStructureBlockPacket.class, GamePacketTypes.SERVERBOUND_SET_STRUCTURE_BLOCK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSetTestBlockPacket.class, GamePacketTypes.SERVERBOUND_SET_TEST_BLOCK, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundTestInstanceBlockActionPacket.class, GamePacketTypes.SERVERBOUND_TEST_INSTANCE_BLOCK_ACTION, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSignUpdatePacket.class, GamePacketTypes.SERVERBOUND_SIGN_UPDATE, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundSwingPacket.class, GamePacketTypes.SERVERBOUND_SWING, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundTeleportToEntityPacket.class, GamePacketTypes.SERVERBOUND_TELEPORT_TO_ENTITY, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundUseItemOnPacket.class, GamePacketTypes.SERVERBOUND_USE_ITEM_ON, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ServerboundUseItemPacket.class, GamePacketTypes.SERVERBOUND_USE_ITEM, PacketFlow.SERVERBOUND));
        temp.add(new PacketInfo(ClientboundResetScorePacket.class, GamePacketTypes.CLIENTBOUND_RESET_SCORE, PacketFlow.CLIENTBOUND));
        temp.add(new PacketInfo(ClientboundTickingStatePacket.class, GamePacketTypes.CLIENTBOUND_TICKING_STATE, PacketFlow.CLIENTBOUND));
        temp.add(new PacketInfo(ClientboundTickingStepPacket.class, GamePacketTypes.CLIENTBOUND_TICKING_STEP, PacketFlow.CLIENTBOUND));
        temp.add(new PacketInfo(ClientboundSetCursorItemPacket.class, GamePacketTypes.CLIENTBOUND_SET_CURSOR_ITEM, PacketFlow.CLIENTBOUND));
        temp.add(new PacketInfo(ClientboundSetPlayerInventoryPacket.class, GamePacketTypes.CLIENTBOUND_SET_PLAYER_INVENTORY, PacketFlow.CLIENTBOUND));
    }

    public static final List<PacketInfo> playPackets = List.copyOf(temp);

    static {
        temp = null;
    }

    public record PacketInfo(Class<? extends Packet<?>> packet, PacketType<?> type, PacketFlow side, PacketTag... tags) {
        public boolean hasTag(PacketTag tag) {
            return Arrays.stream(this.tags()).toList().contains(tag);
        }
    };

    public enum PacketTag {
        CHUNK,
        WORLD,
        ENTITY,
        PLAYER_ANY,
        PLAYER_CLIENT,
        INVENTORY,
        MOVEMENT,
        BLOCK,
        UI,
        DEBUG,
        MISC,
        CHAT,
        COMMAND
    }

    public static @Nullable PacketInfo getInfo(Identifier id) {
        var packets = playPackets.stream().filter((packetInfo -> packetInfo.type().id().equals(id))).toList();
        return packets.isEmpty() ? null : packets.getFirst();
    }

    public static PacketInfo getInfo(PacketType<?> type) {
        return getInfo(type.id());
    }

    public static PacketInfo getInfo(Packet<?> packet) {
        if(packet == null || packet.type() == null) return null;
        return getInfo(packet.type());
    }
}
